"""Closed-loop on-policy recurrent PPO utilities for V20.

V19 constrained the actor only on replay histories.  Small parameter changes
therefore remained free to amplify through the actor's own AR state and visual
closed loop.  V20 instead updates only from a trajectory generated by the
exact pre-update policy.  The causal RGB, joint, executed-action, and AR latent
histories in that trajectory are consequently the histories seen by PPO.
"""

from __future__ import annotations

from dataclasses import dataclass, replace
from typing import Any

import numpy as np
import torch

from .asymmetric_multiview_ppo_v1 import (
    AsymmetricMultiViewPPOConfigV1,
    AsymmetricMultiViewRolloutBatchV1,
    AsymmetricPrivilegedCriticV1,
    PPOUpdateMetricsV1,
    SelectedViewRecurrentActorV1,
    ppo_update_asymmetric_multiview_v1,
)
from .ppo_utils_v1 import state_dict_sha256_v1


ON_POLICY_RECURRENT_PPO_FORMAT_V20 = (
    "edgearm-v20-closed-loop-on-policy-recurrent-ppo-v1"
)
ON_POLICY_RECURRENT_CHECKPOINT_FORMAT_V20 = (
    "edgearm-v20-closed-loop-on-policy-recurrent-ppo-checkpoint-v1"
)
ON_POLICY_RECURRENT_H5_FORMAT_V20 = (
    "edgearm-v20-closed-loop-on-policy-recurrent-trajectory-h5-v1"
)


@dataclass(frozen=True)
class OnPolicyIntrinsicRewardConfigV20:
    valid_contact_bonus: float = 1.5
    maximum_block_displacement_bonus: float = 1.0
    block_displacement_scale_m: float = 0.001
    maximum_positive_potential_bonus: float = 0.15
    positive_potential_scale: float = 0.10
    ik_failure_penalty: float = 0.05

    def validate(self) -> None:
        values = np.asarray(
            [
                self.valid_contact_bonus,
                self.maximum_block_displacement_bonus,
                self.block_displacement_scale_m,
                self.maximum_positive_potential_bonus,
                self.positive_potential_scale,
                self.ik_failure_penalty,
            ],
            dtype=np.float64,
        )
        if not np.all(np.isfinite(values)) or np.any(values < 0.0):
            raise ValueError("V20 intrinsic reward parameters must be finite and non-negative")
        if self.block_displacement_scale_m <= 0.0 or self.positive_potential_scale <= 0.0:
            raise ValueError("V20 intrinsic reward scales must be positive")
        maximum_bonus = (
            self.valid_contact_bonus
            + self.maximum_block_displacement_bonus
            + self.maximum_positive_potential_bonus
        )
        if maximum_bonus >= 4.0 or self.ik_failure_penalty > 0.25:
            raise ValueError("V20 intrinsic reward bound is too large")


@dataclass(frozen=True)
class OnPolicyRewardAuditV20:
    transition_count: int
    source_reward_mean: float
    intrinsic_reward_mean: float
    learning_reward_mean: float
    valid_contact_transition_count: int
    block_motion_transition_count: int
    positive_potential_transition_count: int
    ik_failure_transition_count: int
    maximum_intrinsic_bonus: float
    minimum_intrinsic_bonus: float
    format: str = ON_POLICY_RECURRENT_PPO_FORMAT_V20


def closed_loop_update_gates_v20(
    comparison: dict[str, Any],
) -> dict[str, bool]:
    """Turn an exact paired evaluation into fail-closed update gates."""

    delta = comparison.get("candidate_minus_parent")
    candidate = comparison.get("candidate_totals")
    baseline = comparison.get("parent_totals")
    if not all(type(value) is dict for value in (delta, candidate, baseline)):
        raise TypeError("V20 closed-loop comparison is incomplete")
    return {
        "same_seed_identity": comparison.get("paired_seed_identity") is True,
        "no_safety_regression": comparison.get("safety_regressed") is False,
        "primary_task_improved": comparison.get("primary_task_improved") is True,
        "valid_contact_not_regressed": int(
            candidate["valid_contact_transition_count"]
        )
        >= int(baseline["valid_contact_transition_count"]),
        "mean_final_distance_not_regressed": float(
            delta["mean_final_block_target_distance_m"]
        )
        <= 1.0e-6,
        "mean_final_block_progress_not_regressed": float(
            delta["mean_final_block_progress"]
        )
        >= -1.0e-6,
        "ik_failure_steps_not_regressed": int(
            candidate["ik_failure_step_count"]
        )
        <= int(baseline["ik_failure_step_count"]),
    }


def frontier_balanced_closed_loop_gates_v24(
    comparison: dict[str, Any],
) -> dict[str, bool]:
    """Add per-condition Pareto guards to the aggregate V20 acceptance gate.

    Aggregate metrics can conceal negative transfer: an easy or high-contact
    condition may improve enough to pay for a serious regression elsewhere.
    V24 retains every aggregate gate and additionally bounds each paired
    condition's shield, IK, contact, distance, and normalized block-progress
    deltas.  The small contact/IK tolerances absorb one or two boundary steps;
    safety shields are never allowed to regress.
    """

    checks = closed_loop_update_gates_v20(comparison)
    paired = comparison.get("paired_episodes")
    delta = comparison.get("candidate_minus_parent")
    if not isinstance(paired, list) or not paired or not isinstance(delta, dict):
        raise TypeError("V24 frontier-balanced comparison is incomplete")
    required = (
        "shield_rejection_step_delta",
        "ik_failure_step_delta",
        "valid_contact_transition_delta",
        "final_distance_delta_m",
        "final_block_progress_delta",
        "candidate_safety_violation",
        "parent_safety_violation",
        "candidate_strict_success",
        "parent_strict_success",
    )
    if any(not isinstance(row, dict) or any(name not in row for name in required) for row in paired):
        raise TypeError("V24 frontier-balanced paired episode is incomplete")
    checks.update(
        {
            "same_condition_identity": comparison.get("paired_condition_identity") is True,
            "strict_success_rate_not_regressed": float(delta["strict_success_rate"]) >= 0.0,
            "action_shield_rejections_not_regressed": int(
                delta["action_shield_rejection_step_count"]
            )
            <= 0,
            "every_condition_strict_success_not_regressed": all(
                bool(row["candidate_strict_success"])
                or not bool(row["parent_strict_success"])
                for row in paired
            ),
            "every_condition_safety_not_regressed": all(
                not bool(row["candidate_safety_violation"])
                or bool(row["parent_safety_violation"])
                for row in paired
            ),
            "every_condition_shield_not_regressed": all(
                int(row["shield_rejection_step_delta"]) <= 0 for row in paired
            ),
            "every_condition_ik_regression_bounded": all(
                int(row["ik_failure_step_delta"]) <= 2 for row in paired
            ),
            "every_condition_contact_regression_bounded": all(
                int(row["valid_contact_transition_delta"]) >= -2 for row in paired
            ),
            "every_condition_distance_regression_bounded": all(
                float(row["final_distance_delta_m"]) <= 0.00075 for row in paired
            ),
            "every_condition_progress_regression_bounded": all(
                float(row["final_block_progress_delta"]) >= -0.00375 for row in paired
            ),
        }
    )
    return checks


def compute_intrinsic_reward_v20(
    *,
    valid_contact: np.ndarray,
    block_displacement_m: np.ndarray,
    potential_delta: np.ndarray,
    ik_converged: np.ndarray,
    config: OnPolicyIntrinsicRewardConfigV20,
) -> np.ndarray:
    """Compute the bounded per-transition V20 training-only reward."""

    config.validate()
    contact = np.asarray(valid_contact)
    displacement = np.asarray(block_displacement_m)
    progress = np.asarray(potential_delta)
    feasible = np.asarray(ik_converged)
    if (
        contact.ndim != 1
        or displacement.shape != contact.shape
        or progress.shape != contact.shape
        or feasible.shape != contact.shape
        or contact.dtype != np.dtype(bool)
        or feasible.dtype != np.dtype(bool)
        or displacement.dtype != np.float32
        or progress.dtype != np.float32
        or not np.all(np.isfinite(displacement))
        or not np.all(np.isfinite(progress))
        or np.any(displacement < 0.0)
    ):
        raise ValueError("V20 intrinsic reward inputs are invalid")
    displacement_bonus = np.multiply(
        np.float32(config.maximum_block_displacement_bonus),
        np.clip(
            displacement / np.float32(config.block_displacement_scale_m),
            0.0,
            1.0,
        ),
        dtype=np.float32,
    )
    potential_bonus = np.multiply(
        np.float32(config.maximum_positive_potential_bonus),
        np.clip(
            np.maximum(progress, np.float32(0.0))
            / np.float32(config.positive_potential_scale),
            0.0,
            1.0,
        ),
        dtype=np.float32,
    )
    contact_bonus = np.multiply(
        contact.astype(np.float32),
        np.float32(config.valid_contact_bonus),
        dtype=np.float32,
    )
    ik_penalty = np.multiply(
        (~feasible).astype(np.float32),
        np.float32(config.ik_failure_penalty),
        dtype=np.float32,
    )
    intrinsic = np.subtract(
        np.add(
            np.add(contact_bonus, displacement_bonus, dtype=np.float32),
            potential_bonus,
            dtype=np.float32,
        ),
        ik_penalty,
        dtype=np.float32,
    )
    if not np.all(np.isfinite(intrinsic)):
        raise RuntimeError("V20 intrinsic reward became non-finite")
    return intrinsic


def build_on_policy_learning_batch_v20(
    batch: AsymmetricMultiViewRolloutBatchV1,
    config: OnPolicyIntrinsicRewardConfigV20,
) -> tuple[AsymmetricMultiViewRolloutBatchV1, OnPolicyRewardAuditV20]:
    """Add bounded training-only outcome rewards without changing observations."""

    config.validate()
    batch.validate()
    potential_delta = np.subtract(
        batch.potential_after,
        batch.potential_before,
        dtype=np.float32,
    )
    intrinsic = compute_intrinsic_reward_v20(
        valid_contact=batch.valid_push_side_contact_any,
        block_displacement_m=batch.step_block_displacement_m,
        potential_delta=potential_delta,
        ik_converged=batch.ik_converged,
        config=config,
    )
    learning_rewards = np.add(
        batch.shaped_rewards,
        intrinsic,
        dtype=np.float32,
    )
    if not np.all(np.isfinite(learning_rewards)):
        raise RuntimeError("V20 learning reward became non-finite")
    learning_batch = replace(batch, shaped_rewards=learning_rewards)
    learning_batch.validate()
    audit = OnPolicyRewardAuditV20(
        transition_count=len(learning_rewards),
        source_reward_mean=float(batch.shaped_rewards.mean()),
        intrinsic_reward_mean=float(intrinsic.mean()),
        learning_reward_mean=float(learning_rewards.mean()),
        valid_contact_transition_count=int(
            np.count_nonzero(batch.valid_push_side_contact_any)
        ),
        block_motion_transition_count=int(
            np.count_nonzero(batch.step_block_displacement_m > 0.00005)
        ),
        positive_potential_transition_count=int(
            np.count_nonzero(potential_delta > 0.0)
        ),
        ik_failure_transition_count=int(np.count_nonzero(~batch.ik_converged)),
        maximum_intrinsic_bonus=float(intrinsic.max()),
        minimum_intrinsic_bonus=float(intrinsic.min()),
    )
    return learning_batch, audit


def on_policy_recurrent_ppo_update_v20(
    actor: SelectedViewRecurrentActorV1,
    critic: AsymmetricPrivilegedCriticV1,
    rollout: AsymmetricMultiViewRolloutBatchV1,
    ppo_config: AsymmetricMultiViewPPOConfigV1,
    reward_config: OnPolicyIntrinsicRewardConfigV20,
    *,
    optimizer: torch.optim.Optimizer | None = None,
) -> tuple[PPOUpdateMetricsV1, OnPolicyRewardAuditV20, torch.optim.Optimizer]:
    """Perform exactly one proximal update on the policy's own closed loop."""

    actor_before = state_dict_sha256_v1(actor.state_dict())
    learning_batch, reward_audit = build_on_policy_learning_batch_v20(
        rollout,
        reward_config,
    )
    metrics, updated_optimizer = ppo_update_asymmetric_multiview_v1(
        actor,
        critic,
        learning_batch,
        ppo_config,
        optimizer=optimizer,
    )
    actor_after = state_dict_sha256_v1(actor.state_dict())
    if actor_after == actor_before:
        raise RuntimeError("V20 PPO update did not change the actor")
    if metrics.approximate_kl > ppo_config.target_kl + 1.0e-6:
        raise RuntimeError("V20 PPO update escaped its on-policy KL stop")
    return metrics, reward_audit, updated_optimizer


__all__ = [
    "ON_POLICY_RECURRENT_CHECKPOINT_FORMAT_V20",
    "ON_POLICY_RECURRENT_H5_FORMAT_V20",
    "ON_POLICY_RECURRENT_PPO_FORMAT_V20",
    "OnPolicyIntrinsicRewardConfigV20",
    "OnPolicyRewardAuditV20",
    "build_on_policy_learning_batch_v20",
    "closed_loop_update_gates_v20",
    "compute_intrinsic_reward_v20",
    "frontier_balanced_closed_loop_gates_v24",
    "on_policy_recurrent_ppo_update_v20",
]
